### ISSUE TITLE
catkin build error cannot find livox_driver2

### ISSUE THREAD

**Issue by h-k8888** [brytsknguyen/slict#12]
Hello, nice work.
I meet errors in catkin build , cannot find livox_ros_driver2.
Is  livox_ros_driver2 modified from the original  livox_ros_driver?
```
  CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
    Could not find a package configuration file provided by "livox_ros_driver2"
    with any of the following names:
  
      livox_ros_driver2Config.cmake
      livox_ros_driver2-config.cmake
  
    Add the installation prefix of "livox_ros_driver2" to CMAKE_PREFIX_PATH or
    set "livox_ros_driver2_DIR" to a directory containing one of the above
    files.  If "livox_ros_driver2" provides a separate development package or
    SDK, be sure it has been installed.
  Call Stack (most recent call first):
    CMakeLists.txt:11 (find_package)
```

**Comment by brytsknguyen** [comment]
Hi,

livox_ros_driver2 is the new driver for the latest livox lidars. You can find my fork here:
https://github.com/brytsknguyen/livox_ros_driver2

Otherwise you can [comment out this node ](https://github.com/brytsknguyen/slict/blob/21529f5744ba24055f6442b9ab0b4e1a87be1086/CMakeLists.txt#L142)in the CMakeLists.txt

Regards.

**Comment by h-k8888** [comment]
Thanks for your answer.
I actually cloned your fork, and the errors are still there.
Anyway, I comment out the livox nodes, and then build successfully.
One more question, can SLICT run with only one LiDAR in the NTU VIRAL dataset?

**Comment by brytsknguyen** [comment]
Yes, to run with one lidar, simply comment out the lidar topic and the extrinsic like this 

![image](https://github.com/brytsknguyen/slict/assets/13504903/e7d8abb0-b26a-402c-8914-668071ec2843)

**Comment by h-k8888** [comment]
thanks.
