### ISSUE TITLE
Is the accuracy of SLICT highly depend on the resolution of ufomap?

### ISSUE THREAD

**Issue by h-k8888** [brytsknguyen/slict#13]
Thank you for your excellent work.
We test SLICT in the NTU VIRAL datasets with the horizontal LiDAR only and set the leaf_size to 0.5m.
The trajectory error of SLICT is larger than FASTLIO2 at the same 0.5m map resolution.
However, the default value of the leaf_size in the ntuviral.yaml is set to 0.05.
So, does the accuracy of SLICT highly depend on the resolution of ufomap?

**Comment by brytsknguyen** [comment]
Hi,

A **leaf_size** of 0.5m is too large for SLICT.

Note that the **leaf_size** parameter of SLICT is not the same as the **leaf_size** of FASTLIO2. It is only the smallest voxel size in the ufomap tree, however the appropriate voxel size that a point is associated with will be determined by the algorithm, from **2^1*leaf_size** to **2^6*leaf_size**. 

You can keep the **leaf_size** at 0.05, and set the **surfel_min_depth** to 3 then the smallest surfel size that can be associated with will be 2^3*0.05 = 0.4, which is comparable with setting the map resolution to 0.4m in the case of fastlio.

**Comment by h-k8888** [comment]
I test SLICT again following your advice, keeping **leaf_size** to 0.05 and setting **surfel_min_depth** to 3.
So far, I have test the sequence _eee_ and _nya_, the results are very close to setting **leaf_size** to 0.5m.
Any advice?

**Comment by brytsknguyen** [comment]
Hi,

When you do the evaluation, did you compensate for the offset between the gndtruth measuring point and the IMU (body frame)


https://ntu-aris.github.io/ntu_viral_dataset/evaluation_tutorial.html

**Comment by h-k8888** [comment]
I was negligent because I did not see any information in _readme_ indicating the need for time compensation when evaluating the VIRAL dataset. 
I will test it soon. 
Is time compensation only for SLICT?
I did see that there is a time segmentation in SLICT implementation, but not in FASTLIO.

**Comment by h-k8888** [comment]
I forgot that the ground truth is for crystal prism until I reread the VIRAL paper.
Sorry for that.
I used evo to evaluate SLICT, and  the time difference is set to 0.1 with _**--t_max_diff=0.1**_.
SLICT outperform  FASTLIO2 as shown in your paper.
Nice work.
