### ISSUE TITLE
Why cannot SLICT run the M2DGR dataset?

### ISSUE THREAD

**Issue by h-k8888** [brytsknguyen/slict#14]
Hi, nice work.
I test SLICT using the [M2DGR](https://github.com/SJTU-ViSYS/M2DGR) dataset with launch file
```
      <!-- Run the velodyne to ouster converter -->
      <node pkg="slict" type="slict_velodyne_to_ouster" name="slict_velodyne_to_ouster" respawn="false" output="log" required="true"/>

```
yaml file
```
# To inform the algorithm to exit automatically when no data is received
autoexit:           0

# Declare the lidar topics to merge
lidar_topic:        [
                      "/os_cloud_node/points"
#                      ,
#                      "/os1_cloud_node2/points"
                    ]

merged_lidar_topic: "/merged_pc"

# Lidar extrinsics: Transform of coordinates in lidar's frame to body
# NOTE TO USER: The (4,4) entry of the extrinsics is used to declare
# whether stamp is at beginning (1.000) or end (0.000) of scan
lidar_extr:         [
                      # Horizontal
                      1.0,  0.0,  0.0,  0.27255,
                      0.0,  1.0,  0.0,  0.00053,
                      0.0,  0.0,  1.0,  0.17954,
                      0.0,  0.0,  0.0,  1.000
#                      ,
#                      # Vertical
#                     -1.0,  0.0,  0.0, -0.550,
#                      0.0,  0.0,  1.0,  0.030,
#                      0.0,  1.0,  0.0,  0.090,
#                      0.0,  0.0,  0.0,  0.000
                    ]

```

But the results are very strange. The body will keep moving upwards like this:
![Screenshot from 2023-09-24 15-32-27](https://github.com/brytsknguyen/slict/assets/68782862/06ef1689-cf50-4ecc-b199-b09223cff3b4)

Does the code need to be modified to make the original SLICT  suitable for z-axis upward datasets?
It would be great if you could help me to figure this out.
The same strange things also occur when LVI-SAM runs with the NTU VIRAL dataset,  and the body keeps moving upwards or downwards.

**Comment by brytsknguyen** [comment]
Hi,

I found that the velodyne points have wierd time stamps (negative). I have raised an issue [here.](https://github.com/SJTU-ViSYS/M2DGR/issues/87).

The extrinsics are correct. Please change the imu init time to 0.2 as the robot does not stay static long at the beginning.

![image](https://github.com/brytsknguyen/slict/assets/13504903/d8f5b6bd-d7de-494e-b7ab-25f72204b164)

In the mean time, to make SLICT run with this dataset, please change the callback in the velodynetoouster.cpp file to the following.

    void cloudHandler(const sensor_msgs::PointCloud2ConstPtr &msgIn)
    {
        CloudVelodyne laserCloudVelodyne;
        pcl::fromROSMsg(*msgIn, laserCloudVelodyne);

        int cloudsize = laserCloudVelodyne.size();

        CloudOuster laserCloudOuster;
        laserCloudOuster.points.resize(cloudsize);
        laserCloudOuster.is_dense = true;

        static double hsToOusterIntensity = 1.0;

        #pragma omp parallel for num_threads(NUM_CORE)
        for (size_t i = 0; i < cloudsize; i++)
        {
            auto &src = laserCloudVelodyne.points[i];
            auto &dst = laserCloudOuster.points[i];
            dst.x = src.x;
            dst.y = src.y;
            dst.z = src.z;
            dst.intensity = src.intensity * hsToOusterIntensity;
            dst.ring = src.ring;
            dst.t = (src.time + 0.1) * 1e9f;
            dst.range = sqrt(src.x * src.x + src.y * src.y + src.z * src.z)*1000.0;
        }

        Util::publishCloud(ousterCloudPub, laserCloudOuster, msgIn->header.stamp - ros::Duration(0.1), msgIn->header.frame_id);
    }

**Comment by h-k8888** [comment]
I followed your comment, but the M2DGR dataset still cannot run properly.
However, FASTLIO2 runs with both M2DGR and NTU VIRAL successfully.
If you can figure out why, please let me know.
Thank you.

**Comment by brytsknguyen** [comment]
Which sequence did you try? I tried the gate_01 sequence with the following config file.

```
# To inform the algorithm to exit automatically when no data is received
autoexit:           0

# Declare the lidar topics to merge
lidar_topic:        [
                      "/os_cloud_node/points"
                    ]

merged_lidar_topic: "/merged_pc"

# Lidar extrinsics: Transform of coordinates in lidar's frame to body
# NOTE TO USER: The (4,4) entry of the extrinsics is used to declare
# whether stamp is at beginning (1.000) or end (0.000) of scan
lidar_extr:         [
                      # Horizontal
                      1.0,  0.0,  0.0,  0.27255,
                      0.0,  1.0,  0.0, -0.00053,
                      0.0,  0.0,  1.0,  0.17954,
                      0.0,  0.0, -0.1,  1.000
                    ]

# Minimum lidar range to admit
min_range:          0.0

# IMU topic
imu_topic:          "/handsfree/imu"

# Gravity constant
GRAV:               9.81007

# IMU noises
GYR_N:              5.0e-3
GYR_W:              3.0e-6
ACC_N:              6.0e-2
ACC_W:              8.0e-5

# Weightage of a basic lidar factor
lidar_weight:       1.0

# Number of packets to process at time
WINDOW_SIZE:        4
# Number of substates to give to each packet
N_SUB_SEG:          4

# Downsampling grid size, chose -1 for no downsampling
leaf_size:          0.05          # Downsample scale of input pointcloud, also the scale of ufomap leaf
assoc_spacing:      0.2
surfel_map_depth:   16
surfel_min_point:   10
surfel_min_depth:   2
surfel_query_depth: 7             # Equal to Dmax + 1. Dmax is defined in the paper
surfel_intsect_rad: 0.1           # r in the the paper
surfel_min_plnrty:  0.7

# Distance to surfel and min score thresholds
dis_to_surfel_max:  0.2
score_min:          0.0

# Downsample coefficient of lidar scans, ds_rate = n means keep every n-th point.
ds_rate:            [
                      2
                    ]

# Threshold to add new keyframe
kf_min_dis:         0.5
kf_min_angle:       10

# Optimization parameters
lidar_loss_thres:   10.0

# Solver:
# Trust region strategy: "lm", "dogleg"
trustRegType:       "lm"
# Linear Algebra library used: "eigen", "lapack", "cuda"
linAlgbLib:         "cuda" 
max_solve_time:     0.3
max_iterations:     30

# Sensors fused
fuse_lidar:         1
fuse_imu:           1

regularize_imu:     1
imu_init_time:      0.2
max_outer_iters:    3
max_lidar_factor:   4000  # Maximum number of lidar factors

# Loop closure parameters
loop_en:            1    # Enable loop closure
loop_kf_nbr:        10   # Number of neighbour to check for loop closure
loop_time_mindiff:  10   # Only check for loop when keyframes have this much difference

icpMaxIter:         100   # Maximum iterations for ICP
icpFitnessThres:    0.3   # Fitness threshold for ICP check
histDis:            15    # Maximum correspondence distance for icp

# Bundle adjustment params
rib_edge:           5
odom_q_noise:       0.1
odom_p_noise:       0.1
loop_weight:        0.1

# Number of optimizations before quitting
debug_exit:        -1
publish_map:        0

# Log directory
log_dir:            "/home/tmn/slict_log/ntu_viral"
```

**Comment by h-k8888** [comment]
> Which sequence did you try? I tried the gate_01 sequence with the following config file.
> 
> ```
> # To inform the algorithm to exit automatically when no data is received
> autoexit:           0
> 
> # Declare the lidar topics to merge
> lidar_topic:        [
>                       "/os_cloud_node/points"
>                     ]
> 
> merged_lidar_topic: "/merged_pc"
> 
> # Lidar extrinsics: Transform of coordinates in lidar's frame to body
> # NOTE TO USER: The (4,4) entry of the extrinsics is used to declare
> # whether stamp is at beginning (1.000) or end (0.000) of scan
> lidar_extr:         [
>                       # Horizontal
>                       1.0,  0.0,  0.0,  0.27255,
>                       0.0,  1.0,  0.0, -0.00053,
>                       0.0,  0.0,  1.0,  0.17954,
>                       0.0,  0.0, -0.1,  1.000
>                     ]
> 
> # Minimum lidar range to admit
> min_range:          0.0
> 
> # IMU topic
> imu_topic:          "/handsfree/imu"
> 
> # Gravity constant
> GRAV:               9.81007
> 
> # IMU noises
> GYR_N:              5.0e-3
> GYR_W:              3.0e-6
> ACC_N:              6.0e-2
> ACC_W:              8.0e-5
> 
> # Weightage of a basic lidar factor
> lidar_weight:       1.0
> 
> # Number of packets to process at time
> WINDOW_SIZE:        4
> # Number of substates to give to each packet
> N_SUB_SEG:          4
> 
> # Downsampling grid size, chose -1 for no downsampling
> leaf_size:          0.05          # Downsample scale of input pointcloud, also the scale of ufomap leaf
> assoc_spacing:      0.2
> surfel_map_depth:   16
> surfel_min_point:   10
> surfel_min_depth:   2
> surfel_query_depth: 7             # Equal to Dmax + 1. Dmax is defined in the paper
> surfel_intsect_rad: 0.1           # r in the the paper
> surfel_min_plnrty:  0.7
> 
> # Distance to surfel and min score thresholds
> dis_to_surfel_max:  0.2
> score_min:          0.0
> 
> # Downsample coefficient of lidar scans, ds_rate = n means keep every n-th point.
> ds_rate:            [
>                       2
>                     ]
> 
> # Threshold to add new keyframe
> kf_min_dis:         0.5
> kf_min_angle:       10
> 
> # Optimization parameters
> lidar_loss_thres:   10.0
> 
> # Solver:
> # Trust region strategy: "lm", "dogleg"
> trustRegType:       "lm"
> # Linear Algebra library used: "eigen", "lapack", "cuda"
> linAlgbLib:         "cuda" 
> max_solve_time:     0.3
> max_iterations:     30
> 
> # Sensors fused
> fuse_lidar:         1
> fuse_imu:           1
> 
> regularize_imu:     1
> imu_init_time:      0.2
> max_outer_iters:    3
> max_lidar_factor:   4000  # Maximum number of lidar factors
> 
> # Loop closure parameters
> loop_en:            1    # Enable loop closure
> loop_kf_nbr:        10   # Number of neighbour to check for loop closure
> loop_time_mindiff:  10   # Only check for loop when keyframes have this much difference
> 
> icpMaxIter:         100   # Maximum iterations for ICP
> icpFitnessThres:    0.3   # Fitness threshold for ICP check
> histDis:            15    # Maximum correspondence distance for icp
> 
> # Bundle adjustment params
> rib_edge:           5
> odom_q_noise:       0.1
> odom_p_noise:       0.1
> loop_weight:        0.1
> 
> # Number of optimizations before quitting
> debug_exit:        -1
> publish_map:        0
> 
> # Log directory
> log_dir:            "/home/tmn/slict_log/ntu_viral"
> ```

door02, I will check gate01 with your config file.

What I also want to know is that adjusting the parameter 
```
leaf_size:          0.05          # Downsample scale of input pointcloud, also the scale of ufomap leaf
assoc_spacing:      0.8
surfel_map_depth:   16
surfel_min_point:   10
surfel_min_depth:   1
surfel_query_depth: 7             # Equal to Dmax + 1. Dmax is defined in the paper
```
of SLICT has almost no impact on the accuracy of all sequences in the NTU VIRAL dataset, even if the leaf_size is set to 0.5. 
Of course without loop.
This should be unreasonable, may I ask why?

**Comment by brytsknguyen** [comment]
I also tried 0.5 leaf size and it also works. I don't think it's unreasonable. I think this leaf size will fail if you try it in some small confined area.

**Comment by h-k8888** [comment]
It works, thank you.
