### ISSUE TITLE
Estimator.cpp

### ISSUE THREAD

**Issue by whw-create** [brytsknguyen/slict#15]
Hi, i'm really confused the loop starts from line 603 in Estimator.cpp, it seems that, when not meets WINDOW_SIZE yet, you only used the last element of ssQua, sfQua and other parts.

**Comment by whw-create** [comment]
i think the first 4 lidar scan will initialize the 10 states in line 153 one by one before the frame totally work, but only the last element of these deques was used.

**Comment by brytsknguyen** [comment]
Hi,

Every lidar scan is further split into subsegments set by the N_SUB_SEG param. The imu samples are also distributed into these subsegments. The imu samples in each subsegment will be propagated from the corresponding ssQ, ssP, ssV value.

ss and sf mean state-at-start and state-at-finish of each subsegment. So the sfQ of one subsegment should be equal to ssQ of the next sub-segment. That's the meaning of this [assignment](https://github.com/brytsknguyen/slict/blob/ff23451858ddaaff8ecda2e08b8c3cdcdc8e8607/src/Estimator.cpp#L625)

Line 603 is the loop for integration on each subsegment at the last lidar scan on the sliding window. There is no difference in this step whether the sliding window has reached WINDOW_SIZE length. We simply just integrate the imu samples on the last lidar scan..

**Comment by whw-create** [comment]
what really confused me is that, in line 649, when the window size is less than 4, you will continue to add a new scan, in this new loop, you still use **the back element** of ssQua, ssPos... which were actually initialized already in last loop for last scan. It seems that all first 4 scan's IMU samples repeatedly initialize **the back element** of these states' deque, which means maybe the `mytf(sfQua[i].back(), sfPos[i].back())` you used in line 683 was not initialized correctly yet. Is there anything wrong with my understanding? Thanks for your answer.

**Comment by brytsknguyen** [comment]
Ok I recall the thinking then.

Yes, when the sliding window (SW) has not reached WINDOW_SIZE, all propagations of _the first subsegment of the new segment_ will have the same starting value ssX. the ssX values are initially set to zeros for postion and velocity, ssQ are set to align with gravity at [IMU_INIT part](https://github.com/brytsknguyen/slict/blob/ff23451858ddaaff8ecda2e08b8c3cdcdc8e8607/src/Estimator.cpp#L924)

By right the propagation of one subsegment should start from the sf of the previous subsegment when the sliding window has not filled up. So if one wants to be regorous they have to check for whether this is before the SW has reached its length and write extra code to copy _the sfX of the last subsegment of the previous segment to ssX of the first segment of the current segment_. But then that procedure is only used a few times. If the robot starts from some low vel condition it would not make much different. And we already have the backpropagation done again at the LIOOptimization step below. So I just ignore this.
