### ISSUE TITLE
Question about the lidar_extr in oxford.yaml

### ISSUE THREAD

**Issue by lfwin** [brytsknguyen/slict#21]
Hi, this parameter is the transformation from lidar to body frame, does the body frame is the same as IMU frame?
`
lidar_extr:         [-1.0,  0.0,  0.0, -0.0063; 0.0, -1.0,  0.0,  0.0118; 0.0,  0.0,  1.0,  0.0285;0.0,  0.0,  0.0,  1.0000]
`
because I get this parameter from newercolledge datasets, 
`
T_sensor_2_imu = [1.0000  0  0 0.0063; 0  1.0000   0   -0.0118; 0  0    1.0000    0.0076; 0  0    0  1.0000]
,
T_sensor_2_lidar = [ -1.0000   0   0  0; 0   -1.0000  0 0; 0   0   1.0000    0.0362; 0    0    0  1.0000]
`
So, the transformation form lidar to IMU  is 
`
T_sensor_2_imu * T_sensor_2_lidar'= [-1.0000  0  0.0002    0.0063; 0   -1.0000   -0.0004   -0.0118; 0  0  1.0003     0.0076;  0 0   0.0362  1.0000]
`
but this is not identical with your lidar_extr parameter.

**Comment by brytsknguyen** [comment]
Hi,

The IMU is the body frame. The extrinsic is defined as the transform T_imu_lidar, which means to transform points in the lidar frame to the imu frame. Notice the convention on the frame order. The header of /os1_cloud_node/points topic indicate the frame to be 'os1_lidar'.

The extrinsics are calculated following the extrinsics at page 16 of the user manual here
https://data.ouster.io/downloads/software-user-manual/software-user-manual-v2.1.x.pdf

The term "M_lidar_to_sensor" in this manual is meant to convert coordinates in lidar frame to sensor frame so the frame order is reversed. Anyway, the transform T_imu_lidar is ultimately calculated as follows:

![image](https://github.com/brytsknguyen/slict/assets/13504903/9182e8dd-3338-4d27-a92a-df510f6117e3)
