### ISSUE TITLE
velodyne lidar data 

### ISSUE THREAD

**Issue by MasterBicycle** [brytsknguyen/slict#4]
Thanks for your open source work, I have run this code on open source data and it works amazingly. I am about to run my own data, and the following problem occurs, how to solve it.

rostopic：/velodyne_points

![image](https://user-images.githubusercontent.com/125568810/219370591-f4091ba0-008f-4998-994e-7a5ca7e507f2.png)

**Comment by brytsknguyen** [comment]
Sure thing,

Velodyne points are defined differently from ouster points so you need to convert it to ouster. Please use the node `slict_velodyne_to_ouster` provided in the package.

```
<!-- Run the velodyne to ouster converter -->
<node pkg="slict" type="slict_velodyne_to_ouster" name="slict_velodyne_to_ouster" respawn="false" output="log" required="true"/>
```
Note that the default input is `/velodyne_points` and output is `/os_cloud_node/points`

https://github.com/brytsknguyen/slict/blob/e860a63383ce6a7f9ea9462ab82e46a55fa3fcc4/src/VelodyneToOuster.cpp#L61
https://github.com/brytsknguyen/slict/blob/e860a63383ce6a7f9ea9462ab82e46a55fa3fcc4/src/VelodyneToOuster.cpp#L62

**Comment by MasterBicycle** [comment]
Thank you for your prompt reply, the problem has been resolved
