### ISSUE TITLE
No visualizer in docker?

### ISSUE THREAD

**Issue by YangSiri** [brytsknguyen/slict#5]
Hi, @brytsknguyen 

Is there any viewer such as rviz in the docker image? How to visulize the results? 

Would slict work at Melodic?

**Comment by brytsknguyen** [comment]
Hi,

It's true that i did not set the visualizer inside the docker. I only configure the container to share the host's IP thus you can call rviz outside of the docker at this [line](https://github.com/brytsknguyen/slict/blob/f1f63979afa5c10caaf7300124d51df80b8acda6/docker/run_ntuviral.sh#L15). Is there any reason this does not work for you?

**Comment by YangSiri** [comment]
Thanks, @brytsknguyen 

No problems so far. It works like a charm.
