### ISSUE TITLE
ATE && RPE

### ISSUE THREAD

**Issue by HIT-Ygq** [brytsknguyen/slict#6]
Hello, I would like to know how the ATE, RPE in your paper is evaluated, can you introduce it?

**Comment by brytsknguyen** [comment]
Hi,

I only compare the methods based on the ATE.

ATE is evaluated by comparing the lidar-rate odometry estimate and ground truth, which are from the total station in NTU VIRAL dataset, and from registering the lidar data with the prior map in the Newer College Dataset and the Self-collected dataset.

You can reference to the tutorial on NTU VIRAL dataset for my evaluation method https://ntu-aris.github.io/ntu_viral_dataset/evaluation_tutorial.html

I also have a lecture on this evaluation task. Please find it here https://canvas.kth.se/courses/40649/pages/session-3-observation-models-part-2-imu-+-technical-tutorial-benchmarking-slam?wrap=1

![image](https://user-images.githubusercontent.com/13504903/223058298-7088b9d0-8c05-4c18-842e-b67fd81bee27.png)

**Comment by HIT-Ygq** [comment]
thanks
