### ISSUE TITLE
Derivation about Point2PlaneDisFactorCT?

### ISSUE THREAD

**Issue by Freeecode** [brytsknguyen/slict#8]
Hi Thien-Minh Nguyen,
  Thanks for sharing the excellent work, I am reading the part of joint optimization about constructing the **Point2PlaneDisFactorCT** factor,  and  the derivation of **Rs** confused me,  which equals **Qi * sxPhi**.  
For **Qi**, which derivates through **DRs_DsbxPhi * DsbxPhi_DQi** 
For **Qj**, which derivates  through **DRs_DsxPhi * DsbxPhi_DQj**
Could you give me more details about the derivation of **Rs**?

**Comment by Freeecode** [comment]
Solved!

**Comment by brytsknguyen** [comment]
Hi Houzhan,

Have you worked out the derivation?

The Jacobians are calculated using the chain rule as follows:

![image](https://github.com/brytsknguyen/slict/assets/13504903/758443cd-c673-48fa-a3ab-ef1567e00a7e)
where \bar{s} = 1 - s, also notice that the first equation is derived from Rs = R_{m+1} Exp(-\bar{s}Phi) and the second is from Rs=R_{m}Exp(sPhi). You can find the the formula for the first three derivatives easily from the definition of the right Jacobian (defined in the [VIRAL Fusion paper](https://ieeexplore.ieee.org/document/9502143)).

For the last jacobians in the chains, I use equation (149) in the Micro Lie paper.

**Comment by Freeecode** [comment]
Hi Thien-Minh Nguyen,
Thanks for your kind replay! I have worked  out the  derivation, but only a few questions.  And now your reply solve all my questions. 
Your excellent work work inspried me. Thanks for you again!

**Comment by chengwei0427** [comment]
> Hi Houzhan,
> 
> Have you worked out the derivation?
> 
> The Jacobians are calculated using the chain rule as follows:
> 
> ![image](https://user-images.githubusercontent.com/13504903/243159689-758443cd-c673-48fa-a3ab-ef1567e00a7e.png) where \bar{s} = 1 - s, also notice that the first equation is derived from Rs = R_{m+1} Exp(-\bar{s}Phi) and the second is from Rs=R_{m}Exp(sPhi). You can find the the formula for the first three derivatives easily from the definition of the right Jacobian (defined in the [VIRAL Fusion paper](https://ieeexplore.ieee.org/document/9502143)).
> 
> For the last jacobians in the chains, I use equation (149) in the Micro Lie Paper:
> 
> ![image](https://user-images.githubusercontent.com/13504903/243163824-c5051a74-28cd-4d27-a0eb-de29222b0ae1.png)

Hi, @brytsknguyen ,
Thanks for your nice work!
I'm confused, why isn't the derivative of r with respect to R_m like this
![image](https://github.com/brytsknguyen/slict/assets/20199999/eba90f8d-062a-4112-8b29-5f001d4e9b96)

**Comment by brytsknguyen** [comment]
Hi @chengwei0427,

I am not sure what you mean in this bracket. Why are two similar Jacobians added together?
![image](https://github.com/brytsknguyen/slict/assets/13504903/9d66629c-600d-450c-a73b-937bb2a62a7b)

**Comment by chengwei0427** [comment]
> Hi @chengwei0427,
> 
> I am not sure what you mean in this bracket. Why are two similar Jacobians added together? ![image](https://user-images.githubusercontent.com/13504903/252912652-9d66629c-600d-450c-a73b-937bb2a62a7b.png)

Hi, @brytsknguyen 
Thanks for your reply.
I think the derivative of r with respect to R_m can be broken down into separate derivatives（to R_m）.
Maybe not right. Please point it out. Thanks again.
![image](https://github.com/brytsknguyen/slict/assets/20199999/ed1a8c06-beb2-4a38-a562-bd8aa519f119)

**Comment by snakehaihai** [comment]
> > Hi @chengwei0427,
> > I am not sure what you mean in this bracket. Why are two similar Jacobians added together? ![image](https://user-images.githubusercontent.com/13504903/252912652-9d66629c-600d-450c-a73b-937bb2a62a7b.png)
> 
> Hi, @brytsknguyen Thanks for your reply. I think the derivative of r with respect to R_m can be broken down into separate derivatives（to R_m）. Maybe not right. Please point it out. Thanks again. ![image](https://user-images.githubusercontent.com/20199999/252915747-ed1a8c06-beb2-4a38-a562-bd8aa519f119.png)

去看下tum的那套多视角几何的课程和几篇文章吧。 这里是角度表示 李函数和李代数 不是线性的系统 不能这么微分。

**Comment by chengwei0427** [comment]
> > > Hi @chengwei0427,
> > > I am not sure what you mean in this bracket. Why are two similar Jacobians added together? ![image](https://user-images.githubusercontent.com/13504903/252912652-9d66629c-600d-450c-a73b-937bb2a62a7b.png)
> > 
> > 
> > Hi, @brytsknguyen Thanks for your reply. I think the derivative of r with respect to R_m can be broken down into separate derivatives（to R_m）. Maybe not right. Please point it out. Thanks again. ![image](https://user-images.githubusercontent.com/20199999/252915747-ed1a8c06-beb2-4a38-a562-bd8aa519f119.png)
> 
> 去看下tum的那套多视角几何的课程和几篇文章吧。 这里是角度表示 李函数和李代数 不是线性的系统 不能这么微分。

Hi, @snakehaihai @brytsknguyen 
Here, `(x)'` means perturbation derivation; Maybe not right.

**Comment by chengwei0427** [comment]
Hi, @brytsknguyen 
Thanks for your kindly reply.
The derivation here refers to Mr. Huang's paper <`Intermittent GPS-aided VIO_ Online Initialization and Calibration`>


![image](https://github.com/brytsknguyen/slict/assets/20199999/7cc14169-9246-4f3b-bfa6-b954def15c4f)
![image](https://github.com/brytsknguyen/slict/assets/20199999/ed7e6efe-7791-4cd7-8db7-d689023bc60a)

**Comment by chengwei0427** [comment]
Hi, @brytsknguyen 
Thanks for your kindly reply.
The derivation here refers to Mr. Huang's paper <`Intermittent GPS-aided VIO_ Online Initialization and Calibration`>

![image](https://github.com/brytsknguyen/slict/assets/20199999/004c16ef-43cf-4170-90db-0f0ef629727b)

**Comment by brytsknguyen** [comment]
> Hi, @brytsknguyen Thanks for your kindly reply. The derivation here refers to Mr. Huang's paper <`Intermittent GPS-aided VIO_ Online Initialization and Calibration`>
> 
> ![image](https://user-images.githubusercontent.com/20199999/252925580-004c16ef-43cf-4170-90db-0f0ef629727b.png)
Hi, 

I haven't redone the calculations on that factor in Prof Huang's paper (it's not the same as our jacobian as theta is a R^3 vector, while our is R_m in SO3) however it looks familiar with others that I have done. To calculate it the right way is to pertub theta with a small change, i.e. theta = theta + delta or R_m  = R_m Exp(delta) and then applying the definition of the right and left jacobians of SO3 multiple times.

![image](https://github.com/brytsknguyen/slict/assets/13504903/17c7584f-3749-44a9-b054-bbcdc85d5daf)
